### ISSUE TITLE
issue with vscode

### ISSUE THREAD

**Issue by johnfelipe** [FallenMax/a18n#18]
![SNAG-1217](https://user-images.githubusercontent.com/428820/172544266-6e00436a-c2ce-41eb-b691-8563d13be18f.png)

im using node

	> npx a18n wrap src -write
	npx a18n wrap src -write
		^^^^

	Uncaught SyntaxError: Unexpected identifier

or im do it wrong?

**Comment by FallenMax** [comment]
Hi @johnfelipe , by enter "node" command you have entered node.js repl environment, that's why the `npx ...` command doesn't work.
